name: Running From Safety
favicon: null
layout_spectrum: 0.21017623809166253
typography_spectrum: 0.5406932258047163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9029871807433665
  lightness: 0.3886984798591584
  saturation: 0.7317712048534304
  rhythmicContrast: 0.663872352335602
purpose: []
